#ifndef INCLUDED_SAX_DM
#define INCLUDED_SAX_DM
obj/Characters/SaX
	layer=MOB_LAYER+1
	Right
		pixel_x=32
		icon='SAXBR.dmi'
	RRight
		pixel_x=64
		icon='SAXBRR.dmi'
	LLeft
		pixel_x=-32
		icon='SAXBLL.dmi'
	TopRight
		pixel_x=32
		pixel_y=32
		icon='SAXTR.dmi'
	TRRight
		pixel_x=64
		pixel_y=32
		icon='SAXTRR.dmi'
	TopLeft
		pixel_y=32
		icon='SAXTL.dmi'
	TLLeft
		pixel_y=32
		pixel_x=-32
		icon='SAXTLL.dmi'
#endif